### ISSUE TITLE
Terminate ongoing WorkFlow 

### ISSUE THREAD

**Issue by mattiasrosberg** [j-easy/easy-flows#10]
It would be nice to have some kind of external control of the workflow that runs in your WorkFlowEngine. AFAIC, once a workflow is started there's really no way to stop it from outside. You just have to wait until the entire workflow is finished.

Perhaps there should be a terminate() and/or a close() method on the WorkFlowEngine. 

terminate() just kills the ongoing workflow - no mercy.
close() finish the workflow after the current ongoing work is done (end of call() method).

**Comment by benas** [comment]
How would you propagate the stop signal to the work units currently running? I think this requires a custom implementation of a `WorkflowEngine` that keeps track of what is currently running and stop it when requested (probably by submitting each unit of work to the executor service and keep track of each `Future<WorkReport>` and call `Future#cancel` when needed).

**Comment by fmbenhassine** [comment]
I'm closing this issue as the project will be archived. This can be implemented in a fork. For future reference, an attempt has been made in branch [issue-10](https://github.com/j-easy/easy-flows/tree/issue-10) (see 2625607d46fd7623aa299e19744591f3b7dbf763) based on the previous comments. @mattiasrosberg Thank you for your suggestion anyway!
