### ISSUE TITLE
Did you upload your library to Maven Central Repo

### ISSUE THREAD

**Issue by mcflythekid** [j-easy/easy-flows#17]
I cannot search for this library on maven

**Comment by benas** [comment]
yes, there is a link in the home page to the latest version in maven central:

![Screenshot 2020-04-11 at 20 05 19](https://user-images.githubusercontent.com/1210553/79051343-f7262200-7c2f-11ea-85d7-0d0b91d4cc47.png)

as well as in the getting started section of the wiki: https://github.com/j-easy/easy-flows/wiki/getting-started#use-with-maven.
