### ISSUE TITLE
Use SLF4J instead of JUL

### ISSUE THREAD

**Issue by mcflythekid** [j-easy/easy-flows#19]
I see that this lib use java.util.logging.
How can I use log4j2 while running this library?

**Comment by mcflythekid** [comment]
As described in this post, why don't we use slf4j to let user choose their logging framework

**Comment by benas** [comment]
The main motivation was to have zero dependencies. But SLF4J is better. We replaced JUL with SLF4J in other jeasy projects (see https://github.com/j-easy/easy-batch/issues/315 and https://github.com/j-easy/easy-rules/issues/113), so let me plan this for easy-flows as well to be consistent.

If you want to contribute a PR, you are welcome!
