### ISSUE TITLE
easy-rules and easy-flows

### ISSUE THREAD

**Issue by yanquanyu** [j-easy/easy-flows#2]
How to inject a `context` object like `Fact`  into `WorkFlow` if I want to use easy-rules and easy-flows together?

**Comment by benas** [comment]
Hi @yanquanyu 

You have full control on the workflow creation as well as the rules engine setup. Easy flows does not do any kind of injection into the flows. 

If you want to use easy rules inside a flow, you can pass your facts at construction time to your work and call the rules engine inside the `Work#call` method. Do you see?

This is actually a very interesting use case and I would like to help implementing such an example.
If you have any idea, please don't hesitate to share it.

Kr
Mahmoud

**Comment by yanquanyu** [comment]
@benas thank you for your reply.
I mean how to share a Fact through the whole flow,not just in a flow. The `call` method implements the `Callable` interface and the method doesn't have any parameters, so is there a way to get the same `Fact` Object inside all the `call` methods?

My English is not very good, so if you can't understand what I mean, feel free to contact me and I'll try my best to explain it clearly next time.

**Comment by benas** [comment]
Hi,

You can share a `Facts` object between workflows a construction time:

```java
class FactsAwareWork implements Work {

    private Facts facts;

    public FactsAwareWork(Facts facts) {
        facts = facts;
    }

    public WorkReport call() {
        //add/remove/modify facts here
        return new DefaultWorkReport(WorkStatus.COMPLETED);
    }
}
```

then

```java
Facts facts = new Facts();
// add initial facts
FactsAwareWork work1 = new FactsAwareWork(facts);
FactsAwareWork work2 = new FactsAwareWork(facts);

WorkFlow workflow = .. // define your workflow

WorkFlowEngine workFlowEngine = aNewWorkFlowEngine().build();
WorkReport workReport = workFlowEngine.run(workflow);
```

Does this helps?

Kr
Mahmoud

**Comment by yanquanyu** [comment]
@benas  Thank you very much, It is very helpful.

**Comment by benas** [comment]
Glad it helped!

**Comment by benas** [comment]
I was asked the same question by another user and gave a more generic API `ExecutionContext` (than `Facts` which is specific to easy rules) in the following example: https://gist.github.com/benas/4d55e8b18f2ba05ab94a14eda98bd6e9

This gist shows how to share an execution context between steps in a workflow.

Hope this helps.
