### ISSUE TITLE
Separate asynchronous flow, that can execute outside the WorkFlowEngine thread

### ISSUE THREAD

**Issue by arunav-b** [j-easy/easy-flows#20]
The current `ParallelFlow` is intended to execute on the `WorkFlowEngine` thread and waits for the completion of all the async threads before the next `Work` in the `WorkFlow` can be executed. This is very well suited when we have a Work that is dependent on the completion of `ParallelWork`. But suppose we want to execute a `WorkFlow` asynchronously without any dependent `Work`, such that both WorkFlowEngine thread and the asynchronous WorkFlow can complete independently. Typically this flow is suited for asynchronous notification to different systems/users as a part of complex service flows.
&nbsp;

I have worked on an asyncFlow using the easy-flows and this is how the flow looks like -
```
public void WorkFlow buildWorkFlow(List<Work> works){
      AsyncFlow asyncFlow = AsyncFlow.Builder.asyncFlow(new ForkJoinPool(10))
                .named("asyncFlow")
                .execute(works)
                .onSuccess(successWork)
                .onFailure(failureWork)
                .build();
}
```

The asyncFlow WorkFlow will be initiated and completed by the `WorkFlowEngine` thread, however the individual `Works` inside the `execute` method will be executed in separate threads. Since these threads can run long after the `WorkFlowEngine` has completed processing, so we cannot maintain the `WorkReport` on the `WorkFlowEngine` thread. As an alternative, the asyncFlow is providing two methods - `onSuccess` and `onFailure`. `onSuccess` will execute when all the `Works` inside the asyncFlow has completed successfully and `onFailure` will execute if any one (or more) of the `Work` from the input list of `Works` has failed. The `WorkReport` for the individual `Works` will be set inside the `WorkContext`. Since these two works only have access to `WorkContext` (as the `WorkReport` of the `WorkFlowEngine` may be completed sometime in past), so I am setting the `WorkReports` of the individual asynchronous `Works` inside the `WorkContext` inside a key `easyflows.async.workReports`. By doing a get on this key, the `WorkReports` of the individual async Works can be accessed from `successWork` and `failureWork`.

Please let me know your thoughts on this. I'll fork and submit the change for review.

**Comment by benas** [comment]
> But suppose we want to execute a WorkFlow asynchronously without any dependent Work, such that both WorkFlowEngine thread and the asynchronous WorkFlow can complete independently. 

> Since these threads can run long after the WorkFlowEngine has completed processing, [..]

This would be a design flaw. When `workFlowEngine.run()` returns, all work units should have finished. As a user, I would not expect things to be still running after this method. The engine's thread can spawn other threads (like in the `ParallelFlow` where a separate `ExecutorService` is used), but should not leave other threads running after the engine has completed processing (the final report would be undefined in this case).

> As an alternative, the asyncFlow is providing two methods - onSuccess and onFailure. onSuccess will execute when all the Works inside the asyncFlow has completed successfully and onFailure will execute if any one (or more) of the Work from the input list of Works has failed

This can be achieved using a composition of a parallel flow inside a conditional flow:

```java
ConditionalFlow conditionalFlow = aNewConditionalFlow()
        .execute(aNewParallelFlow(executorService).execute(works).build())
        .when(WorkReportPredicate.COMPLETED)
        .then(successWork)
        .otherwise(failureWork)
        .build();
```

That's the whole idea of the library: define a set of small, focused flows that do one thing and do it well and which are composable to create more complex workflows (following the unix philosophy).

> Since these two works only have access to WorkContext (as the WorkReport of the WorkFlowEngine may be completed sometime in past), so I am setting the WorkReports of the individual asynchronous Works inside the WorkContext inside a key easyflows.async.workReports. By doing a get on this key, the WorkReports of the individual async Works can be accessed from successWork and failureWork.

This seems convoluted to me. If the engine "may be completed sometime in past", it means work units might finish after the engine has returned, which is problematic as described previously.

I'm closing this issue, but feel free to add a comment if you want. Thank you for your suggestion anyway!

**Comment by hzn6426** [comment]
You can refer to the following [Easy Work](https://github.com/hzn6426/easy-work), a similar Java process engine.
