### ISSUE TITLE
Error handling while flow execution , would better to be handled 

### ISSUE THREAD

**Issue by arkabandyopadhyay** [j-easy/easy-flows#4]
It would be great if there is some sort of flow redirection based on error handling because in case of werror the whole work flow is getting terminated.

**Comment by benas** [comment]
Hi @arkabandyopadhyay 

As said on gitter, error handling is left to the user. You can always return a status of failed + the exception (see [here](https://github.com/j-easy/easy-flows/blob/master/src/main/java/org/jeasy/flows/work/DefaultWorkReport.java#L51)) and use a custom predicate to redirect the flow as you need (using a conditional flow for instance).

Do you see?

Kr
Mahmoud

**Comment by benas** [comment]
Any update on this?

> flow redirection based on error handling

As said, this is a use case for conditional flow. In your work unit, you can handle errors and redirect according a predicate based on the status.

**Comment by benas** [comment]
No updates, I'm closing this issue.

**Comment by hzn6426** [comment]
You can refer to the following [Easy Work](https://github.com/hzn6426/easy-work), a similar Java process engine.
