### ISSUE TITLE
Suspend Flow for user task

### ISSUE THREAD

**Issue by ivan86to** [j-easy/easy-flows#5]
Hello, beautifull engine! 
How i can suspend a Work for user action?

**Comment by benas** [comment]
> Hello, beautifull engine!

Oh thanks!

> How i can suspend a Work for user action?

This is not possible out of the box. Since the execution context is not persisted, it's not possible to suspend/resume executions. But you can still design a work that persists its state somewhere and resume where it was suspended on a subsequent execution.

Does this help?

**Comment by ivan86to** [comment]
Yes, it could be fine. In this case I could create two different Workflows. When the first one finishes, I save the status of the document on the database, waiting for a user to start the second Flow or not.
I do a trial because it seems to me the right way.

**Comment by benas** [comment]
Ah ok I understand better your use case now, you need to suspend the workflow (at a specific work/step) to let the user do a manual action and decide to continue the flow or not. Is that correct?

In this case, I can imagine a work step like the following :

```java
public class Step implements Work {

    @Override
    public String getName() {
        return "step2";
    }

    @Override
    public WorkReport call() {
        while(shouldWaitForUser()) {
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                return new DefaultWorkReport(WorkStatus.FAILED);
            }
        }
        return new DefaultWorkReport(WorkStatus.COMPLETED);
    }

    private boolean shouldWaitForUser() {
        // implement user notification to resume the flow
        return false;
    }
}
```

This step can be in the middle of flow (and hence does not require you to create two separate flows).

I tried something similar with the following:

```java
public class Step1 implements Work {

    @Override
    public String getName() { return "step1"; }

    @Override
    public WorkReport call() {
        System.out.println("Step 1");
        return new DefaultWorkReport(WorkStatus.COMPLETED);
    }
}

public class Step2 implements Work {

    @Override
    public String getName() {
        return "step2";
    }

    @Override
    public WorkReport call() {
        try {
            System.out.println("Press any key to resume");
            System.in.read();
        } catch (IOException e) {
            new DefaultWorkReport(WorkStatus.FAILED);
        }
        return new DefaultWorkReport(WorkStatus.COMPLETED);
    }
}

public class Step3 implements Work {

    @Override
    public String getName() { return "step3"; }

    @Override
    public WorkReport call() {
        System.out.println("Step 3");
        return new DefaultWorkReport(WorkStatus.COMPLETED);
    }
}

public class WorkflowTest {
    public static void main(String[] args) {
        WorkFlow workFlow = SequentialFlow.Builder.aNewSequentialFlow()
                .execute(new Step1())
                .then(new Step2())
                .then(new Step3())
                .build();
        WorkFlowEngine workFlowEngine = aNewWorkFlowEngine().build();
        WorkReport workReport = workFlowEngine.run(workFlow);
    }
}
```

Here, step2 would wait for the user to press any key to continue, but as said previously, this could be any check. When I run the example, the workflow is suspended until I press a key to resume it:

```java
Step 1
Press any key to resume

Step 3
```

Hope this helps!

**Comment by ivan86to** [comment]
But an infinite loop does not create problems if the users are 100/200 and that the open workflows are about 1500/2000 per day? I could find myself at the end of the day with 2000 infinite loops waiting for an ok from a user until the next day.
But the solution you proposed could be a very interesting starting point.

**Comment by ivan86to** [comment]
What do you think about this solution? With observable?
https://www.javaworld.com/article/2077258/learn-java/observer-and-observable.html

**Comment by benas** [comment]
> But an infinite loop does not create problems if the users are 100/200 and that the open workflows are about 1500/2000 per day? I could find myself at the end of the day with 2000 infinite loops waiting for an ok from a user until the next day.

Of course! Don't do that in production 😄 That was just an example to illustrate the idea.
Using a step as an observer of an observable object that the user modifies in order to let the workflow continue is definitely an elegant idea!!

In the same way, the step could be a listener (observer) for an event (observable) from the user telling the workflow to continue. But you got the idea..

So to answer your question: Suspending a workflow is an implementation detail, there is no need to change any API to support this.

If this helped, I let you close the issue.

> Hello, beautifull engine!

Thank you. If you find the engine useful, please spread the word!

**Comment by ivan86to** [comment]
Ok, perfect!! Thank you for support and examples!

**Comment by hzn6426** [comment]
You can refer to the following [Easy Work](https://github.com/hzn6426/easy-work), a similar Java process engine.
