### ISSUE TITLE
Run Workflow inside another workflow

### ISSUE THREAD

**Issue by paraglohiya** [j-easy/easy-flows#6]
Hi,

I liked the framework its a very easy implementation of thread 🥇 
Is there an option I can run a Workflow Engine in another Workflow Engine.

Like a Master Workflow and a several Child workflow inside master.

**Comment by benas** [comment]
Thank you, I'm glad you like Easy Flows!

> Is there an option I can run a Workflow Engine in another Workflow Engine.

Are you looking for workflow engines inception? 😄 

![inception](https://media.giphy.com/media/96FloqY8aYqwo/giphy.gif)

Joke aside, I don't understand what you mean by that, may be a code example could help. What I can tell you is that a workflow is also a work, this is what makes workflows composable. A workflow can be defined by assembling other workflows. Once you have defined your workflow of workflows, you can use the same engine to run it.

I'm closing this issue for now, but don't hesitate to add comments if necessary.
