### ISSUE TITLE
patch to support exchange data between workers

### ISSUE THREAD

**Issue by zhaoyta** [j-easy/easy-flows#8]
i have  a patch to support exchange data before worker.

this is my code https://github.com/zhaoyta/easy-flows/commits/master .  two commit

**Comment by benas** [comment]
Thanks! Please open a PR and we can discuss the changes there. It is easier to review that viewing the changes in your fork.

**Comment by zhaoyta** [comment]
hi, benas ,i submit a pr on https://github.com/j-easy/easy-flows/pull/9,thanks

**Comment by benas** [comment]
Thanks! I'm closing this issue, let's continue the discussion in the PR.
